# Generated by Django 2.0.1 on 2018-01-05 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='price_value',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True),
        ),
    ]
